version: "3"
services:
  api:
    build: ./server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5152
      - EWS_USER=${EWS_USER}
      - EWS_PWD=${EWS_PWD}
      - TZ=${TZ}
    container_name: scheduler-server
  client:
    build: ./client
    ports:
      - "443:443"
    container_name: scheduler-client
    volumes:
      - ./client/crt/rootCA.crt:/etc/nginx/ssl/rootCA.crt:ro
      - ./client/crt/rootCA.key:/etc/nginx/ssl/rootCA.key:ro
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro