version: "3"
services:
  api:
    build: ./server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5152
      - TZ=${TZ}
    container_name: scheduler-server
    ports:
      - 5152:5152
      - 7151:7151
    volumes:
      - ./server/data:/var/server/data   
  client:
    build: ./client
    ports:
      - "443:443"
    container_name: scheduler-client
    volumes:
      - ./client/crt/rootCA.crt:/etc/nginx/ssl/rootCA.crt:ro
      - ./client/crt/rootCA.key:/etc/nginx/ssl/rootCA.key:ro
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
